Repository eclipse/lyo.core, pull requests merged in 2019-02, with the labels that each got.

#71 Clean up POM files
  oslc-query/pom.xml
  oslc-trs/pom.xml
  oslc4j-core-build/pom.xml
  oslc4j-core/pom.xml
  oslc4j-jena-provider/pom.xml
  oslc4j-json4j-provider/pom.xml
  oslc4j-utils/pom.xml
  shacl/pom.xml
Labels: enhancement

#70 Only depend on oslc4j-jena-provider in oslc-trs for tests
  oslc-trs/pom.xml
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance, Xtra: Fix Verified

#75 Fix javac warnings
  oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/NestedWildcardProperties.java
  oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/SingletonWildcardProperties.java
  oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/model/Property.java
  oslc4j-core/src/test/java/org/eclipse/lyo/oslc4j/core/OSLC4JUtilsTest.java
  oslc4j-core/src/test/java/org/eclipse/lyo/oslc4j/core/test/OslcGlobalNamespaceProviderTest.java
  oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/AbstractOslcRdfXmlProvider.java
  oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/JenaModelHelper.java
  oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/RdfXmlAbbreviatedWriter.java
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/JenaCustomNamespaceTest.java
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/JenaOslcNameTest.java
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/RdfXmlAbbreviatedWriterTest.java
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/TypesTest.java
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/UnparseableLiteralTest.java
  oslc4j-utils/src/main/java/org/eclipse/lyo/core/utils/marshallers/OSLC4JMarshaller.java
Labels: Priority: Low, Status: Review Needed, Type: Maintenance, Xtra: Fix Verified

#63 Update Lyo Core to use Jax-rs 2.0, and be independent of Wink
  oslc4j-core-build/pom.xml
  oslc4j-core/pom.xml
  oslc4j-jena-provider/pom.xml
  oslc4j-jena-provider/src/test/java/org/eclipse/lyo/oslc4j/provider/jena/test/JsonLdTest.java
  oslc4j-json4j-provider/pom.xml
  oslc4j-utils/pom.xml
Labels: Priority: High, Status: Changes Requested, Type: Enhancement
